#ifndef EXIT_STATUS_H
#define EXIT_STATUS_H

typedef enum {
    PARSE_SUCCESS = 0,
    ERR_INVALID_INT,
    ERR_OVERFLOW,
    ERR_NEGATIVE,
    ERR_NULL_PTR,
    ERR_TRAILING_GARBAGE,
} ParseExitResult;

typedef enum {
    YN_SUCCESS,
    ERR_INVALID_INPUT,
    ERR_INPUT_EXCEED_RANGE
} YesNoResult;

typedef enum {
    PARSED_STRING_SUCCESS = 0,
    ERR_EMPTY_STRING,
    ERR_EXCEEDED_MAX_SIZE,
    ERR_STRING_NULL_PTR
} ParsedStringResult;

typedef enum {
    OPERATION_SUCCESS = 0,
    ERR_ACCOUNT_NULL,
    ERR_INVALID_PIN,
    ERR_MISMATCH_PIN,
    ERR_INPUT_STR_ERROR,
    ERR_UPDATE_OPERATION_FAIL
} Credentials;

typedef enum {
    NOTIF_SUCCESS_ENABLED,
    NOTIF_SUCCESS_DISABLED,
    NOTIF_WARN_ALREADY_SET,
    NOTIF_ERR_SESSION_NULL,
} NotificationsStatus;

typedef enum {
    STATUS_OPERATION_SUCCESS = 0,
    STATUS_OPERATION_WARN_ALREADY_SET,
    STATUS_OPERATION_ERR_CLOSE_INCOMPATIBLE,
    STATUS_OPERATION_ERR_OUT_OF_RANGE,
    STATUS_OPERATION_ERR_SESSION_NULL
} AccountStateStatus;

typedef enum {
    AUTH_OPERATION_SUCCESS = 0,
    AUTH_REGISTRATION_SUCCESS,
    AUTH_LOGIN_SUCCESS,
    AUTH_ERR_SESSION_NULL,
    AUTH_ERR_NOT_FOUND,
    AUTH_ERR_CLOSED,
    AUTH_ERR_BAD_PIN,
    AUTH_ERR_DB_FULL
} AuthStatus;

typedef enum {
    TXN_OPERATION_SUCCESS,
    TXN_ERR_NULL,
    TXN_INVALID_PIN,
    TXN_MISMATCH_PIN,
    TXN_INVALID_BAL,
    TXN_INSUFFICIENT_BAL,
    TXN_BAL_OVERFLOW,
    TXN_ERR_RECEIVER_NOT_FOUND,
    TXN_ERR_SELF_TRANSFER
} TransactionStatus;

typedef enum {
    FILE_OK = 0,
    FILE_NOT_FOUND,
    FILE_PERMISSION_DENIED,
    FILE_WRITE_FAILED,
    FILE_CORRUPTED
} FileStatus;

#endif