#ifndef EXIT_STATUS_H
#define EXIT_STATUS_H

typedef enum {
    PARSE_SUCCESS = 0,
    ERR_INVALID_INT,
    ERR_INVALID_DOUBLE,
    ERR_NULL_PTR,
    ERR_TRAILING_GARBAGE,
} ParseExitResult;

typedef enum {
    YN_SUCCESS,
    ERR_INVALID_INPUT,
    ERR_INPUT_EXCEED_RANGE
} YesNoResult;

typedef enum {
    PARSED_STRING_SUCCESS = 0,
    ERR_EMPTY_STRING,
    ERR_EXCEEDED_MAX_SIZE,
    ERR_STRING_NULL_PTR
} ParsedStringResult;

typedef enum {
    OPERATION_SUCCESS = 0,
    ERR_ACCOUNT_NULL,
    ERR_INVALID_PIN,
    ERR_MISMATCH_PIN,
    ERR_INPUT_STR_ERROR,
    ERR_UPDATE_OPERATION_FAIL
} Credentials;

#endif