name: C/C++ CI

on:
    push:
        branches: [ "development", "staging", "main" ]
    pull_request:
        branches: [ "development", "staging", "main" ]

jobs:
    build:
        name: Build and Test
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Install build tools and Valgrind
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential valgrind

            - name: Set up Make (Win64)
              if: matrix.os == 'windows-latest'
              run: |
                echo "Using built-in Windows build tools"

            - name: Compile project
              run: make all

            - name: Run Memory Leak Checks
              if: matrix.os == 'ubuntu-latest'
              run: echo "0" | make memcheck
